"""
Django settings for hms project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ===============================
# SECURITY SETTINGS
# ===============================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--_5g*4jot1$%$p4resafe!$^@v2h-5)rn)vgyjd&#%2t1r5qgh"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']


# ===============================
# APPLICATION DEFINITION
# ===============================
INSTALLED_APPS = [
    # Django Core Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    'hmsapp',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hms.urls"


# ===============================
# TEMPLATES CONFIGURATION
# ===============================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ['templates'],  # Global templates folder
        "APP_DIRS": True,  # Also look for templates in app directories
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Custom context processors
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "hmsapp.context_processors.hms_stats",
                "hmsapp.context_processors.doctor_session",
                'hmsapp.context_processors.user_type_check',
            ],
        },
    },
]

WSGI_APPLICATION = "hms.wsgi.application"


# ===============================
# DATABASE CONFIGURATION
# ===============================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
    # For PostgreSQL (production):
    # "default": {
    #     "ENGINE": "django.db.backends.postgresql",
    #     "NAME": "hms_db",
    #     "USER": "hms_user",
    #     "PASSWORD": "your_password",
    #     "HOST": "localhost",
    #     "PORT": "5432",
    # }
}


# ===============================
# PASSWORD VALIDATION
# ===============================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ===============================
# INTERNATIONALIZATION
# ===============================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ===============================
# STATIC FILES (CSS, JavaScript, Images)
# ===============================
# URL to use when referring to static files
STATIC_URL = "static/"

# Additional directories where Django will look for static files
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Global static folder at project root
]

# Directory where static files will be collected during deployment
STATIC_ROOT = BASE_DIR / "staticfiles"


# ===============================
# MEDIA FILES (User-uploaded files)
# ===============================
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# ===============================
# DEFAULT PRIMARY KEY FIELD TYPE
# ===============================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ===============================
# SESSION CONFIGURATION
# ===============================
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# ===============================
# MESSAGES CONFIGURATION
# ===============================
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}


# ===============================
# LOGIN/LOGOUT REDIRECTS
# ===============================
LOGIN_REDIRECT_URL = '/admin-dashboard/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/admin/login/'


# ===============================
# CRISPY FORMS (Optional - if installed)
# ===============================
# CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
# CRISPY_TEMPLATE_PACK = "bootstrap5"
