# Generated by Django 6.0.1 on 2026-01-30 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "emergency_load",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("total_beds", models.PositiveIntegerField(default=100)),
                ("available_beds", models.PositiveIntegerField(default=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="hospitals/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("patient_id", models.CharField(max_length=20, unique=True)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("doctor_id", models.CharField(max_length=20, unique=True)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("general", "General Medicine"),
                            ("cardiology", "Cardiology"),
                            ("orthopedics", "Orthopedics"),
                            ("emergency", "Emergency Medicine"),
                            ("pediatrics", "Pediatrics"),
                            ("outpatient", "Outpatient"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("offline", "Offline"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("password", models.CharField(default="doctor123", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DoctorActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("case_assigned", "Case Assigned"),
                            ("case_updated", "Case Updated"),
                            ("case_completed", "Case Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hmsapp.doctor"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="HomeCareRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                (
                    "issue",
                    models.CharField(
                        choices=[
                            ("heart_attack", "Heart Attack Symptoms"),
                            ("breathing", "Breathing Difficulty"),
                            ("stroke", "Stroke Symptoms"),
                            ("weakness", "Severe Weakness"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("home_visit", "Doctor Home Visit"),
                            ("call_assist", "Doctor On Call Assistance"),
                        ],
                        default="home_visit",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Doctor En Route", "Doctor En Route"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("eta", models.CharField(default="15-20 mins", max_length=50)),
                ("token", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hmsapp.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                (
                    "symptom",
                    models.CharField(
                        choices=[
                            ("pain", "Chest Pain / Breathing Difficulty"),
                            ("trauma", "Severe Physical Injury"),
                            ("burn", "Burns"),
                            ("fever", "High Fever / Flu"),
                            ("stroke", "Stroke Symptoms"),
                            ("weakness", "Severe Weakness"),
                            ("routine", "Routine Checkup"),
                        ],
                        max_length=50,
                    ),
                ),
                ("symptom_description", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Low",
                        max_length=20,
                    ),
                ),
                ("score", models.PositiveIntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("Doctor Assigned", "Doctor Assigned"),
                            ("In Progress", "In Progress"),
                            ("Doctor En Route", "Doctor En Route"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Waiting",
                        max_length=30,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("Hospital Emergency", "Hospital Emergency"),
                            ("Home Assistance", "Home Assistance"),
                            ("Doctor Home Visit", "Doctor Home Visit"),
                            ("Doctor On Call", "Doctor On Call Assistance"),
                        ],
                        default="Hospital Emergency",
                        max_length=30,
                    ),
                ),
                ("token", models.CharField(max_length=20, unique=True)),
                ("eta", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hmsapp.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hmsapp.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["score", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Confirmed", "Confirmed"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hmsapp.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hmsapp.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["appointment_date", "appointment_time"],
            },
        ),
    ]
