# Generated by Django 6.0.1 on 2026-02-01 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hmsapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hmsapp.hospital",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_location",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="emergencycase",
            name="assigned_hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hmsapp.hospital",
            ),
        ),
        migrations.AddField(
            model_name="emergencycase",
            name="patient_location",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="emergencycase",
            name="patient_phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="patient",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="patient",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("doctor", "appointment_date", "appointment_time")},
        ),
    ]
